name: waste_free
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies: # এখানে ভুল ছিল, এটি এখন ঠিক করা হয়েছে
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.5.3
  intl: ^0.20.2
  mobile_scanner: ^5.1.0
  permission_handler: ^11.3.0
  geolocator: ^10.1.0
  flutter_map: ^6.2.1
  latlong2: ^0.9.1
  image_picker: ^0.8.7
  image: ^4.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true